accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.index, name="index"),
    path('login', views.user_login, name="login"),
    path('signup', views.user_signup, name="signup"),
    path('logout', views.user_logout, name="logout"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("accounts.urls")),
    path('admin/', admin.site.urls),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
    
class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "password1", "password2"]

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput) 

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .forms import SignupForm, LoginForm
from django.contrib import messages

# Create your views here.
def index(req):
    return render(req, "index.html")

# signup page
def user_signup(req):
    if req.method == "POST":
        form = SignupForm(req.POST)
        print(form)
        if form.is_valid():
            # breakpoint()
            form.save()
            return redirect('accounts:login')
    else:
        form = SignupForm()
    return render(req, "signup.html", {'form':form})

# login page
def user_login(req):
    if req.method == "POST":
        form = LoginForm(req.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(req, username=username, password=password)
            if user:
                login(req, user)
                messages.success(req, "登入成功")
                return redirect('accounts:index')
            else :
                messages.error(req, "登入失敗")
    else:
        form = LoginForm()
    return render(req, "login.html", {'form':form})

# logout page
def user_logout(req):
    logout(req)
    return redirect('accounts:login')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.13.10/dist/cdn.min.js"></script>
</head>
<body>
    {% if messages %}
        <div class="flash">
            {% for message in messages %}
            <p class="{{ message.tags }}">
                <span>{{ message }}</span>
            </p>
            {% endfor %}
        </div>
    {% endif %}

    <main class="main">
        {% block content %}{% endblock %}
    </main>
</body>
</html>

templates/index.html
{% extends "base.html" %}

{% block content %}
    {% if request.user.is_authenticated %}
        <p>{{ request.user.username }}</p>
        <a href="{% url 'accounts:logout' %}">logout</a>
    {% else %}
        <a href="{% url 'accounts:login' %}">login</a>
        <a href="{% url 'accounts:signup' %}">signup</a>
    {% endif %}
    <h1>WELCOME</h1>
{% endblock content %}

templates/login.html
{% extends "base.html" %}

{% block content %}
    <h1>Login</h1>
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Login</button>
        <a href="{% url 'accounts:signup' %}">Dont have Account Create</a>
    </form>
{% endblock content %}

templates/signup.html
{% extends "base.html" %}

{% block content %}
    <h1>Signup</h1>
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">signup</button>
        <a href="{% url 'accounts:login' %}">Already have account?</a>
    </form>
{% endblock content %}